function genes=checkGeneID(gene)
%% Function written by Eleni Christoforidou in MATLAB R2019b

%This function prints the gene IDs of a particular gene. Both the gene_id 
%and the db_xref are printed.

%Run this function from inside the folder containing the "GTF_gene_IDs.csv"
%file. This file is generated by running the custom function "getGTFgeneID".

%INPUT ARGUMENTS:
%gene:    A character array matching the exact name of a gene, using its
%         gene_id name in a GTF file.

%OUTPUT ARGUMENTS:
%An m x 2 cell array of characters, where column 1 shows the gene_id name
%and column 2 shows the db_xref name of the input gene. If a 0 x 0 cell
%array, then the input gene is not found in the CSV file. If the input gene
%has an ambiguous name (i.e., it may be referring to two or more different
%genes with the same name), then the db_xref column will have more than one
%unique character array.

%%
list=table2cell(readtable('GTF_gene_IDs.csv'));
indices=[];
for ii=1:length(list)
    text=list{ii,1};
    if strcmp(text,gene)==1
        indices=[indices,ii];
    end
end
genes=list(indices,:);
end