function getMappedIDs
%% Function written by Eleni Christoforidou in MATLAB R2019b

%This function creates a TXT file containing the read IDs of the mapped
%reads only.

%NOTE: The custom functions "flag_analysis", "qname_analysis" and "countqnames"
%must be run  beforehand, to generate the appropriate variables to be used
%in the current function.

%Run this function from inside the folder containing subfolders with the 
%MAT files generated by the above functions.

%INPUT ARGUMENTS: None.

%OUTPUT ARGUMENTS: None, but a TXT file is saved in each folder containing
%MAT files.

%%
%Find MAT files to work with.
D=dir('*/qname_analysis.mat'); %get list of MAT files in subfolders.
d=length(D); %number of MAT files found.
fprintf('%d MAT files found.\n',d) %inform user.
wd=cd; %save working directory.

for f=1:d %loop through each MAT file.
    cd(D(f).folder); %navigate to folder containing MAT file.
    fprintf('Loading data for file %d of %d...\n',f,d); %inform user of progress.
    load('qname_analysis.mat','mappedQNAMEs'); %load the read IDs for the mapped reads.
    mappedQNAMEs=mappedQNAMEs';
    foldername=split(pwd,'\'); %separate path into its folder parts.
    foldername=foldername{end}; %get name of current folder.
    filename=strcat(foldername,'_mapped_IDs.txt'); %append current folder name to new filename.
    writecell(mappedQNAMEs,filename); %save TXT file containing read IDs for mapped reads.
    cd(wd); %return to working directory for next iteration of for-loop.
end
clear
end