function plotCompareAlignments
%% Function written by Eleni Christoforidou in MATLAB R2019b

%This function creates a plot comparing the number of reads that aligned at
%least once by two different aligners.

%The custom functions "qname_analysis" and "countqnames" must be ran beforehand to
%generate the variables used in the current function.

%Run this function from one directory above the folder containing the 
%subfolders with the MAT files generated by the above functions.

%IMPORTANT: This function creates a plot for 6 samples. A lot of things are
%hardcoded so this code will need to be modified for use with new samples.

%INPUT ARGUMENTS: None.

%OUTPUT ARGUMENTS: None, but the plot is saved in 2 different formats in
%the working directory.

%% Obtain data.

%Find MAT files to work with.
F=dir('*Data analysis*'); %get names of folders containing the subfolders with the SAM files.
masterdir=cd; %save master directory.

for ii=1:length(F) %loop through each master folder.
    cd(F(ii).folder); %navigate to folder containing subfolders.

D=dir('*/qname_analysis.mat'); %get list of MAT files in subfolders.
d=length(D); %number of MAT files found.
fprintf('%d MAT files found.\n',d) %inform user.
wd=cd; %save working directory.

%Initialise variables.
high_quality=zeros(d,1);
aligned_guppy=zeros(d,1); %number of reads that aligned at least once by Guppy aligner.
aligned_minimap2=zeros(d,1); %number of reads that aligned at least once by minimap2 aligner.

for f=1:d %loop through each MAT file.
    cd(D(f).folder); %navigate to folder containing MAT file.
    load('qname_analysis.mat','unique_qnames','unique_mapped') %load the data into the workspace.
    high_quality(f)=length(unique_qnames); %this is the number of reads that were used for the alingment.
    aligned(f)=length(unique_mapped); %this is the number of reads that aligned at least once.
    clear unique_qnames unique_mapped
end
cd(wd); %return to working directory.


%% Create plot.

for f=1:d %loop through each MAT file.
    cd(D(f).folder); %navigate to folder containing MAT file.
    load('qname_analysis.mat','');
end

linkaxes(ax,'xy'); %link axes limits of all subplots.

%Save figure.
savefig(fig,'CompareAlignments'); %save figure as a FIG file in the working directory.
fig.Renderer='painters'; %force MATLAB to render the image as a vector.
saveas(fig,'CompareAlignments.svg'); %save figure as an SVG file.
close
clear
end
